### Pipeline of NLP

In [191]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [192]:
df = pd.read_csv('train.txt', sep=';', names=['text', 'emotion'])

In [193]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

## 1. Lowercasing the text

In [194]:
def lowercase (text):
    return text.lower()

df['text'] = df['text'].apply(lowercase)
df.head(1)

                      text  emotion
0  i didnt feel humiliated  sadness

## Converting the emotions into numberical values

In [195]:
unique_emotion = df['emotion'].unique()
emotion_to_number = {}
i = 0
for emotion in unique_emotion: 
    emotion_to_number[emotion] = i
    i += 1

print(emotion_to_number)

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [196]:
df['emotion'] = df['emotion'].map(emotion_to_number)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

## Removing the punctuations

In [197]:
import string
def remove_punctuations(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df['text'] = df['text'].apply(remove_punctuations)
df.head(2)

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0

## Remove Numbers

In [198]:
def remove_number(text):
    cleaned_text = ""
    for ch in text: 
        if not ch.isdigit(): 
            cleaned_text += ch

    return cleaned_text

df['text'] = df['text'].apply(remove_number)

df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [199]:
def remove_emoji (text):
    cleaned_text = ""
    for i in text: 
        if i.isascii(): 
            cleaned_text += i
    
    return cleaned_text

df['text'] = df['text'].apply(remove_emoji)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

## Remove stop words

In [200]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [201]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [202]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'was', 'had', 'has', "hasn't", 're', 'to', 'himself', 'having', 'same', "mightn't", 'own', "she's", 'again', "they'll", 'she', 'am', 'they', 'aren', 'more', "shouldn't", 'why', 'some', 'do', 'other', 'ours', "we'll", 'won', 'up', 'isn', 'most', 'its', 'where', 'so', 'any', 'mustn', 'under', 'no', 'shan', "it'd", 'in', 'below', 'wouldn', 'were', 'his', 'wasn', 'needn', 'of', 'after', "don't", 'all', 'if', 'd', 'those', 'out', 'being', 'here', 't', 'have', 'their', 'above', "you'll", 'between', 'too', 'this', 'then', "won't", 've', 'themselves', 'at', "weren't", 'll', 'whom', 'such', 'it', 'he', "shan't", 'that', 'further', "he'd", 'yours', "you're", "you'd", 'how', 'does', "they'd", 'but', 'm', "he's", 'an', "he'll", 'my', 'now', 'will', 'both', "wouldn't", 'be', 'them', 'ourselves', 'which', "i've", 'very', 'doing', 'or', 'than', 'are', "wasn't", 'once', 'when', "hadn't", 'only', 'against', 'itself', 'o', 'y', "that'll", 'couldn', 's', 'through', "it'll", 'theirs', 'haven', 'hadn', "i'll", 'shouldn', "we're", "we've", 'ain', "it's", 'is', "doesn't", 'with', "aren't", 'each', 'ma', 'me', 'the', 'on', "they've", 'myself', 'just', 'for', "i'm", "should've", "isn't", 'our', 'we', 'these', 'by', 'mightn', 'your', 'yourselves', 'while', 'before', 'weren', 'until', "we'd", 'hers', 'about', 'doesn', 'been', "you've", "mustn't", 'off', 'who', 'hasn', 'did', "they're", "didn't", 'don', 'you', "haven't", 'into', "she'd", 'what', "couldn't", 'him', 'should', 'can', 'her', 'i', 'during', 'didn', 'a', 'herself', "she'll", 'yourself', 'because', 'as', "needn't", 'there', 'few', 'over', "i'd", 'from', 'and', 'down', 'nor', 'not'}

In [203]:
def remove_stopwords (text):
    cleaned_text = []
    tokenized = text.split()

    for ch in tokenized: 
        if ch not in stop_words: 
            cleaned_text.append(ch)

    return ' '.join(cleaned_text)

df['text'] = df['text'].apply(remove_stopwords)
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1