In [22]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [15]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [16]:
X = df.drop('species', axis=1)
y = df['species']

In [17]:
model = KNeighborsClassifier()

In [18]:
params = {
    "n_neighbors": [5,6,7,8,8,10],
    "weights": ['uniform', 'distance']
}

In [20]:
gridmodel = GridSearchCV(model, params, cv=5)
gridmodel.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [5, 6, 7, 8, 8, 10],
                         'weights': ['uniform', 'distance']})

In [21]:
gridmodel.cv_results_

{'mean_fit_time': array([0.00610762, 0.00611157, 0.00299988, 0.00210218, 0.00251503,
        0.00200434, 0.00239854, 0.00239477, 0.00230808, 0.00220351,
        0.00239525, 0.00241342]),
 'std_fit_time': array([5.72892148e-03, 4.49810630e-03, 6.32258914e-04, 2.04300957e-04,
        4.53754777e-04, 1.23770247e-05, 4.91269461e-04, 4.93450058e-04,
        4.00724098e-04, 4.07910580e-04, 4.93880449e-04, 6.11000789e-04]),
 'mean_score_time': array([0.00520015, 0.00600572, 0.00420022, 0.00231214, 0.00380125,
        0.00259624, 0.00380235, 0.00260663, 0.00380349, 0.00240059,
        0.00379987, 0.00271144]),
 'std_score_time': array([0.00292555, 0.0035887 , 0.00074846, 0.00040662, 0.00040873,
        0.00049217, 0.00039807, 0.00048367, 0.00074422, 0.00048895,
        0.00074781, 0.00052604]),
 'param_n_neighbors': masked_array(data=[5, 5, 6, 6, 7, 7, 8, 8, 8, 8, 10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'n_neighbors': 5, 'weights': 'uniform'},
  {'n_neighbors': 5, 'weights': 'distance'},
  {'n_neighbors': 6, 'weights': 'uniform'},
  {'n_neighbors': 6, 'weights': 'distance'},
  {'n_neighbors': 7, 'weights': 'uniform'},
  {'n_neighbors': 7, 'weights': 'distance'},
  {'n_neighbors': 8, 'weights': 'uniform'},
  {'n_neighbors': 8, 'weights': 'distance'},
  {'n_neighbors': 8, 'weights': 'uniform'},
  {'n_neighbors': 8, 'weights': 'distance'},
  {'n_neighbors': 10, 'weights': 'uniform'},
  {'n_neighbors': 10, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.93333333, 0.9       , 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        1.        , 1.        ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        0.93333333, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.97333333, 0.96666667, 0.98      , 0.98      , 0.98      ,
        0.98      , 0.96666667, 0.98      , 0.96666667, 0.98      ,
        0.98      , 0.98666667]),
 'std_test_score': array([0.02494438, 0.03651484, 0.01632993, 0.01632993, 0.01632993,
        0.01632993, 0.02981424, 0.01632993, 0.02981424, 0.01632993,
        0.02666667, 0.01632993]),
 'rank_test_score': array([ 9, 10,  2,  2,  2,  2, 10,  2, 10,  2,  2,  1], dtype=int32)}

In [24]:
result = pd.DataFrame(gridmodel.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006108,0.005729,0.005200,0.002926,5,uniform,"{'n_neighbors': 5, 'weights': 'uniform'}",0.966667,1.0,0.933333,0.966667,1.0,0.973333,0.024944,9
1,0.006112,0.004498,0.006006,0.003589,5,distance,"{'n_neighbors': 5, 'weights': 'distance'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,10
2,0.003000,0.000632,0.004200,0.000748,6,uniform,"{'n_neighbors': 6, 'weights': 'uniform'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
3,0.002102,0.000204,0.002312,0.000407,6,distance,"{'n_neighbors': 6, 'weights': 'distance'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
4,0.002515,0.000454,0.003801,0.000409,7,uniform,"{'n_neighbors': 7, 'weights': 'uniform'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
5,0.002004,0.000012,0.002596,0.000492,7,distance,"{'n_neighbors': 7, 'weights': 'distance'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
6,0.002399,0.000491,0.003802,0.000398,8,uniform,"{'n_neighbors': 8, 'weights': 'uniform'}",0.966667,1.0,0.933333,0.933333,1.0,0.966667,0.029814,10
7,0.002395,0.000493,0.002607,0.000484,8,distance,"{'n_neighbors': 8, 'weights': 'distance'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
8,0.002308,0.000401,0.003803,0.000744,8,uniform,"{'n_neighbors': 8, 'weights': 'uniform'}",0.966667,1.0,0.933333,0.933333,1.0,0.966667,0.029814,10
9,0.002204,0.000408,0.002401,0.000489,8,distance,"{'n_neighbors': 8, 'weights': 'distance'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
10,0.002395,0.000494,0.003800,0.000748,10,uniform,"{'n_neighbors': 10, 'weights': 'uniform'}",0.966667,1.0,1.000000,0.933333,1.0,0.980000,0.026667,2
11,0.002413,0.000611,0.002711,0.000526,10,distance,"{'n_neighbors': 10, 'weights': 'distance'}",0.966667,1.0,1.000000,0.966667,1.0,0.986667,0.016330,1

In [26]:
result[['params', 'mean_test_score']]

                                        params  mean_test_score
0     {'n_neighbors': 5, 'weights': 'uniform'}         0.973333
1    {'n_neighbors': 5, 'weights': 'distance'}         0.966667
2     {'n_neighbors': 6, 'weights': 'uniform'}         0.980000
3    {'n_neighbors': 6, 'weights': 'distance'}         0.980000
4     {'n_neighbors': 7, 'weights': 'uniform'}         0.980000
5    {'n_neighbors': 7, 'weights': 'distance'}         0.980000
6     {'n_neighbors': 8, 'weights': 'uniform'}         0.966667
7    {'n_neighbors': 8, 'weights': 'distance'}         0.980000
8     {'n_neighbors': 8, 'weights': 'uniform'}         0.966667
9    {'n_neighbors': 8, 'weights': 'distance'}         0.980000
10   {'n_neighbors': 10, 'weights': 'uniform'}         0.980000
11  {'n_neighbors': 10, 'weights': 'distance'}         0.986667