In [9]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsClassifier

In [10]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
X = df.drop('species', axis=1)
y = df['species']

In [12]:
model = KNeighborsClassifier()

In [13]:
params = {
    "n_neighbors": [5,6,7,8,8,10],
    "weights": ['uniform', 'distance']
}

In [14]:
gridmodel = RandomizedSearchCV(model, params, cv=5)
gridmodel.fit(X, y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'n_neighbors': [5, 6, 7, 8, 8, 10],
                                        'weights': ['uniform', 'distance']})

In [15]:
gridmodel.cv_results_

{'mean_fit_time': array([0.0024045 , 0.00220242, 0.00191264, 0.00200901, 0.00199862,
        0.00185022, 0.00184841, 0.0023489 , 0.00228004, 0.00221281]),
 'std_fit_time': array([4.95741508e-04, 4.04763345e-04, 4.70082153e-04, 8.82548164e-06,
        1.31800413e-06, 4.33169976e-04, 3.89885674e-04, 1.10070332e-03,
        3.89773425e-04, 7.02657995e-04]),
 'mean_score_time': array([0.00392699, 0.00249486, 0.00304685, 0.00200009, 0.00241365,
        0.00281339, 0.0025094 , 0.00290117, 0.00273581, 0.00229201]),
 'std_score_time': array([6.28175887e-04, 4.49557748e-04, 7.79463266e-04, 1.63486316e-05,
        5.06906576e-04, 7.54953783e-04, 4.52458274e-04, 1.95320241e-04,
        6.24045324e-04, 5.72427281e-04]),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'distance', 'uniform', 'distance', 'uniform',
                    'distance', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[7, 5, 6, 7, 8, 8, 10, 8, 8, 6],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'weights': 'uniform', 'n_neighbors': 7},
  {'weights': 'distance', 'n_neighbors': 5},
  {'weights': 'uniform', 'n_neighbors': 6},
  {'weights': 'distance', 'n_neighbors': 7},
  {'weights': 'distance', 'n_neighbors': 8},
  {'weights': 'uniform', 'n_neighbors': 8},
  {'weights': 'distance', 'n_neighbors': 10},
  {'weights': 'uniform', 'n_neighbors': 8},
  {'weights': 'distance', 'n_neighbors': 8},
  {'weights': 'distance', 'n_neighbors': 6}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       , 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 1.        , 0.93333333, 0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.96666667, 0.93333333, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.96666667, 0.98      , 0.98      , 0.98      ,
        0.96666667, 0.98666667, 0.96666667, 0.98      , 0.98      ]),
 'std_test_score': array([0.01632993, 0.03651484, 0.01632993, 0.01632993, 0.01632993,
        0.02981424, 0.01632993, 0.02981424, 0.01632993, 0.01632993]),
 'rank_test_score': array([2, 8, 2, 2, 2, 8, 1, 8, 2, 2], dtype=int32)}

In [16]:
result = pd.DataFrame(gridmodel.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_weights,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002404,0.000496,0.003927,0.000628,uniform,7,"{'weights': 'uniform', 'n_neighbors': 7}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
1,0.002202,0.000405,0.002495,0.000450,distance,5,"{'weights': 'distance', 'n_neighbors': 5}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,8
2,0.001913,0.000470,0.003047,0.000779,uniform,6,"{'weights': 'uniform', 'n_neighbors': 6}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
3,0.002009,0.000009,0.002000,0.000016,distance,7,"{'weights': 'distance', 'n_neighbors': 7}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
4,0.001999,0.000001,0.002414,0.000507,distance,8,"{'weights': 'distance', 'n_neighbors': 8}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
5,0.001850,0.000433,0.002813,0.000755,uniform,8,"{'weights': 'uniform', 'n_neighbors': 8}",0.966667,1.0,0.933333,0.933333,1.0,0.966667,0.029814,8
6,0.001848,0.000390,0.002509,0.000452,distance,10,"{'weights': 'distance', 'n_neighbors': 10}",0.966667,1.0,1.000000,0.966667,1.0,0.986667,0.016330,1
7,0.002349,0.001101,0.002901,0.000195,uniform,8,"{'weights': 'uniform', 'n_neighbors': 8}",0.966667,1.0,0.933333,0.933333,1.0,0.966667,0.029814,8
8,0.002280,0.000390,0.002736,0.000624,distance,8,"{'weights': 'distance', 'n_neighbors': 8}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2
9,0.002213,0.000703,0.002292,0.000572,distance,6,"{'weights': 'distance', 'n_neighbors': 6}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,2

In [17]:
result[['params', 'mean_test_score']]

                                       params  mean_test_score
0    {'weights': 'uniform', 'n_neighbors': 7}         0.980000
1   {'weights': 'distance', 'n_neighbors': 5}         0.966667
2    {'weights': 'uniform', 'n_neighbors': 6}         0.980000
3   {'weights': 'distance', 'n_neighbors': 7}         0.980000
4   {'weights': 'distance', 'n_neighbors': 8}         0.980000
5    {'weights': 'uniform', 'n_neighbors': 8}         0.966667
6  {'weights': 'distance', 'n_neighbors': 10}         0.986667
7    {'weights': 'uniform', 'n_neighbors': 8}         0.966667
8   {'weights': 'distance', 'n_neighbors': 8}         0.980000
9   {'weights': 'distance', 'n_neighbors': 6}         0.980000