In [2]:
from PyPDF2 import PdfReader
import re
import string
import pickle
reader = PdfReader(r"C:\Users\HP\OneDrive\Desktop\ML-DS\10_Resume_Classifier\MOHIT's Resume-hackerresume (2).pdf")

In [3]:
print(f'number of pages in the resume is {len(reader.pages)}')
text = reader.pages[0].extract_text()
text

number of pages in the resume is 1

'MOHIT GOS W AMI\nmohitgos w ami18326@gmail.c om | +91 7900927236\nGitHub | Linkedin | LeetCode | Portfolio\nEDUC A TION\nMEER UT INS TITUTE OF ENGINEERING AND TECHNOL OG Y A ugus t - 2023 - A u gus t - 2 027\nBachelor of Technology in Computer Science and enginnering ( AI&ML) - 4th sem Meeru t\nCGP A: Curren t 8.6\nARMY PUBLIC SCHOOL March- 2022 - March- 2023\nSenior Secondary (Class 12), CBSE Meeru t\nPercen tage: 90.4%\nEXPERIENCE\nFRE SHER\nSKILL S\nProgramming Languages C, C++, python, ja v a Script\nLibraries/Frameworks React, T ail windc ss, Node.js, Express.js\nTools / Platforms v sC ode, git/GitHub\nDatabases MongoDB\nPR O JEC T S / OPEN-SOURCE\nALGO SPRINT | Link React.js Node.js Express.js T ail windc ss shadcn MongoDB Web Socke ts\nA full - stack web applica tion f or c oding pr actice fea turing per sonalized c oding r ooms, real - time ba ttles,\nleaderboar ds, c ollabor a tive c ompiler, and MCQ challenges.\nPERSONAL POR TF OL OIO WEBSITE | Link React, tail windc ss, fr amer -mo tion\nDe veloped a per sonal portf olio website t o sho wcase my skills, pr oject and achie vmen ts. The website\npr o vides a clean and modern user in terf ace using T ail wind C SS. I t is full y responsive, and highligh ts my\ntechnical e xpertise, The website serves as a cen tr al hub f or sharing my w ork.\nMONEY MENT OR AI | Link React, tail wind c ss, fr amer -mo tion\nBuil t the responsive fr on tend f or Mone y Men t or AI, a per sonal finance assistan t tha t uses AI t o pr o vide\nbudge ting advice, and st ock s insigh ts. Designed and implemen ted dynamic UI c omponen ts, and\nensured a user - friendl y in terf ace using modern web design principles.\nCER TIFIC A TIONS\n• GFG- 160 Challenge - geeks for geeks\n• eduskills virtual In ternship full stack web de velopmen t - Eduskills\nHONORS & A W ARD S\n• W on a gfg bagpack\n• Cleared tc s c ode vita r ound 1 - 2024\n1'

In [98]:
text = text.lower()
text = re.sub(f"[{string.punctuation}]", "", text)
text = re.sub(r"\d+", "", text)
text = re.sub(r"\s+", " ", text)
text = re.sub(r'http\S+|www\S+', '', text)   
text

'mohit gos w ami mohitgos w amigmailc om github linkedin leetcode portfolio educ a tion meer ut ins titute of engineering and technol og y a ugus t a u gus t bachelor of technology in computer science and enginnering aiml th sem meeru t cgp a curren t army public school march march senior secondary class cbse meeru t percen tage experience fre sher skill s programming languages c c python ja v a script librariesframeworks react t ail windc ss nodejs expressjs tools platforms v sc ode gitgithub databases mongodb pr o jec t s opensource algo sprint link reactjs nodejs expressjs t ail windc ss shadcn mongodb web socke ts a full stack web applica tion f or c oding pr actice fea turing per sonalized c oding r ooms real time ba ttles leaderboar ds c ollabor a tive c ompiler and mcq challenges personal por tf ol oio website link react tail windc ss fr amer mo tion de veloped a per sonal portf olio website t o sho wcase my skills pr oject and achie vmen ts the website pr o vides a clean and modern user in terf ace using t ail wind c ss i t is full y responsive and highligh ts my technical e xpertise the website serves as a cen tr al hub f or sharing my w ork money ment or ai link react tail wind c ss fr amer mo tion buil t the responsive fr on tend f or mone y men t or ai a per sonal finance assistan t tha t uses ai t o pr o vide budge ting advice and st ock s insigh ts designed and implemen ted dynamic ui c omponen ts and ensured a user friendl y in terf ace using modern web design principles cer tific a tions • gfg challenge geeks for geeks • eduskills virtual in ternship full stack web de velopmen t eduskills honors a w ard s • w on a gfg bagpack • cleared tc s c ode vita r ound '

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.corpus import stopwords

In [5]:
df = pd.read_csv("UpdatedResumeDataSet.csv")
df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  962 non-null    object
 1   Resume    962 non-null    object
dtypes: object(2)
memory usage: 15.2+ KB

In [7]:
def remove_number(text):
    cleaned_text = ""
    for ch in text: 
        if not ch.isdigit(): 
            cleaned_text += ch

    return cleaned_text

df['Resume'] = df['Resume'].apply(remove_number)

df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay  to May  B.E   UIT-R...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [20]:
def remove_emoji (text):
    cleaned_text = ""
    for i in text: 
        if i.isascii(): 
            cleaned_text += i
    
    return cleaned_text

df['Resume'] = df['Resume'].apply(remove_emoji)
df.head()

   Category                                             Resume
0         0  Skills * Programming Languages: Python (pandas...
1         0  Education Details May May B.E UIT-RGPV Data Sc...
2         0  Areas Interest Deep Learning, Control System D...
3         0  Skills  R  Python  SAP HANA  Tableau  SAP HANA...
4         0  Education Details MCA YMCAUST, Faridabad, Hary...

In [8]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'her', 'both', 'above', 'only', 'while', 'didn', 'not', 'y', 'between', 'they', "you've", 'can', "they'll", 'wouldn', 'weren', 'were', 'against', 'now', 'have', 't', 'down', 'needn', 'shouldn', 'doing', 'how', "it's", "mustn't", "she'd", "it'll", 'very', 'me', 'who', 'until', 'he', 'you', 'should', 've', 'do', "they're", "he'd", 'him', 'more', 'she', "i'll", 'ma', "you'll", 'isn', 'that', 'where', 'all', 'will', 'few', 'doesn', 'himself', 'mustn', 'of', "needn't", 'with', 'won', 'it', "hadn't", 'his', "she's", 'own', 'there', "we'll", "you'd", 'below', 'during', 'had', 'for', "he's", 's', 'themselves', "it'd", 'ours', "couldn't", 'here', 'nor', 'ain', 'its', 'other', 'which', 'into', "shan't", 'too', 'an', 'by', 'wasn', 'what', 'yourself', 'll', 'those', "they've", 'been', 'ourselves', 'does', 'couldn', 'some', 'myself', "we've", 'this', "aren't", 'in', 'theirs', 'yours', 'to', 'yourselves', 'if', 'are', "they'd", 'each', "she'll", 'a', 'don', "that'll", 'over', 'any', "shouldn't", 'when', 'be', 'about', 'and', "don't", 'their', 'we', 'shan', "didn't", "haven't", "i'd", "i'm", 'the', "doesn't", 'did', 'o', 'i', 'them', "we're", 'as', "won't", 'before', 'our', 'being', 'your', 'at', "you're", 'off', 'hadn', 'from', 'through', "wasn't", 'just', 'why', 'but', 'm', 'up', 'once', 'my', "mightn't", 'on', 'having', 'am', 'most', 'd', 'these', 'was', 'because', "should've", 'further', 'or', 'so', 'same', 'whom', "we'd", 'hasn', 'itself', 'haven', "weren't", "he'll", 'after', 'is', 'out', 'again', 'then', 'mightn', 'herself', 'than', 're', "wouldn't", 'has', 'such', "isn't", 'aren', "i've", "hasn't", 'no', 'hers', 'under'}

In [10]:
def remove_stopwords (text):
    cleaned_text = []
    tokenized = text.split()

    for ch in tokenized: 
        if ch not in stop_words: 
            cleaned_text.append(ch)

    return ' '.join(cleaned_text)

df['Resume'] = df['Resume'].apply(remove_stopwords)
df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details May May B.E UIT-RGPV Data Sc...
2  Data Science  Areas Interest Deep Learning, Control System D...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details MCA YMCAUST, Faridabad, Hary...

In [11]:
category = df['Category'].unique()

In [12]:
i = 0
category_to_number = {}
for cat in category: 
    category_to_number[cat] = i
    i+= 1

category_to_number

{'Data Science': 0,
 'HR': 1,
 'Advocate': 2,
 'Arts': 3,
 'Web Designing': 4,
 'Mechanical Engineer': 5,
 'Sales': 6,
 'Health and fitness': 7,
 'Civil Engineer': 8,
 'Java Developer': 9,
 'Business Analyst': 10,
 'SAP Developer': 11,
 'Automation Testing': 12,
 'Electrical Engineering': 13,
 'Operations Manager': 14,
 'Python Developer': 15,
 'DevOps Engineer': 16,
 'Network Security Engineer': 17,
 'PMO': 18,
 'Database': 19,
 'Hadoop': 20,
 'ETL Developer': 21,
 'DotNet Developer': 22,
 'Blockchain': 23,
 'Testing': 24}

In [13]:
df['Category'] = df['Category'].map(category_to_number)
df['Category']

0       0
1       0
2       0
3       0
4       0
       ..
957    24
958    24
959    24
960    24
961    24
Name: Category, Length: 962, dtype: int64

In [14]:
vectorizer = CountVectorizer()

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df['Resume'], df['Category'], train_size=0.8, random_state=42)
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

In [112]:
models = {'LR': LogisticRegression(), 'NB': MultinomialNB(), 'SVM': SVC()}
accuracy = {}

for name, model in models.items(): 
    model.fit(X_train_vectorized, y_train)
    y_pred = model.predict(X_test_vectorized)
    acc = accuracy_score(y_pred, y_test)

    accuracy[name] = acc

print(accuracy)

{'LR': 0.9844559585492227, 'NB': 0.9948186528497409, 'SVM': 0.927461139896373}

In [113]:
from sklearn.model_selection import cross_val_score
for name, model in models.items(): 
    acc = cross_val_score(model, vectorizer.fit_transform(df['Resume']), df['Category'], cv=5)
    print(np.mean(acc))

0.9958549222797928
0.9937715889464593
0.9459628670120898

In [16]:
model = LogisticRegression()
model.fit(X_train_vectorized, y_train)
y_pred_train = model.predict(X_train_vectorized)
train_accuracy = accuracy_score(y_pred_train, y_train)

y_pred = model.predict(X_test_vectorized)
test_accuracy = accuracy_score(y_pred, y_test)

In [17]:
print(train_accuracy, test_accuracy)

1.0 0.9844559585492227

In [18]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_pred))
labels = ['Negative', 'Positive']
cm = confusion_matrix(y_test, y_pred)

print(cm)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       0.86      1.00      0.92        12
           2       1.00      0.33      0.50         3
           3       1.00      1.00      1.00         6
           4       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         8
           6       1.00      1.00      1.00         8
           7       1.00      1.00      1.00         7
           8       1.00      1.00      1.00         9
           9       1.00      1.00      1.00        15
          10       0.80      1.00      0.89         4
          11       1.00      1.00      1.00         7
          12       1.00      1.00      1.00         5
          13       1.00      1.00      1.00         6
          14       1.00      1.00      1.00        12
          15       1.00      1.00      1.00        10
          16       1.00      0.93      0.96        14
          17       1.00      1.00      1.00         3
          18       1.00      1.00      1.00         7
          19       1.00      1.00      1.00         8
          20       1.00      1.00      1.00         4
          21       1.00      1.00      1.00         7
          22       1.00      1.00      1.00         5
          23       1.00      1.00      1.00         7
          24       1.00      1.00      1.00        16

    accuracy                           0.98       193
   macro avg       0.99      0.97      0.97       193
weighted avg       0.99      0.98      0.98       193

[[ 5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  4  0  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0 13  0  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  0  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  4  0  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7  0  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  5  0
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  7
   0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  16]]

In [22]:
text = remove_number(text)
text = remove_emoji(text)

text = remove_stopwords(text)
input_vectorised = vectorizer.transform([text])

In [19]:
y_pred = model.predict(input_vectorised)

In [21]:
print('HR')

HR

In [23]:
with open("model.pkl", "wb") as f:
    pickle.dump({"model", model}, f)