In [2]:
from PyPDF2 import PdfReader
import re
import string
reader = PdfReader(r"C:\Users\HP\OneDrive\Desktop\ML-DS\10_Resume_Classifier\MOHIT's Resume-hackerresume (2).pdf")

In [3]:
print(f'number of pages in the resume is {len(reader.pages)}')
text = reader.pages[0].extract_text()
text

number of pages in the resume is 1

'MOHIT GOS W AMI\nmohitgos w ami18326@gmail.c om | +91 7900927236\nGitHub | Linkedin | LeetCode | Portfolio\nEDUC A TION\nMEER UT INS TITUTE OF ENGINEERING AND TECHNOL OG Y A ugus t - 2023 - A u gus t - 2 027\nBachelor of Technology in Computer Science and enginnering ( AI&ML) - 4th sem Meeru t\nCGP A: Curren t 8.6\nARMY PUBLIC SCHOOL March- 2022 - March- 2023\nSenior Secondary (Class 12), CBSE Meeru t\nPercen tage: 90.4%\nEXPERIENCE\nFRE SHER\nSKILL S\nProgramming Languages C, C++, python, ja v a Script\nLibraries/Frameworks React, T ail windc ss, Node.js, Express.js\nTools / Platforms v sC ode, git/GitHub\nDatabases MongoDB\nPR O JEC T S / OPEN-SOURCE\nALGO SPRINT | Link React.js Node.js Express.js T ail windc ss shadcn MongoDB Web Socke ts\nA full - stack web applica tion f or c oding pr actice fea turing per sonalized c oding r ooms, real - time ba ttles,\nleaderboar ds, c ollabor a tive c ompiler, and MCQ challenges.\nPERSONAL POR TF OL OIO WEBSITE | Link React, tail windc ss, fr amer -mo tion\nDe veloped a per sonal portf olio website t o sho wcase my skills, pr oject and achie vmen ts. The website\npr o vides a clean and modern user in terf ace using T ail wind C SS. I t is full y responsive, and highligh ts my\ntechnical e xpertise, The website serves as a cen tr al hub f or sharing my w ork.\nMONEY MENT OR AI | Link React, tail wind c ss, fr amer -mo tion\nBuil t the responsive fr on tend f or Mone y Men t or AI, a per sonal finance assistan t tha t uses AI t o pr o vide\nbudge ting advice, and st ock s insigh ts. Designed and implemen ted dynamic UI c omponen ts, and\nensured a user - friendl y in terf ace using modern web design principles.\nCER TIFIC A TIONS\n• GFG- 160 Challenge - geeks for geeks\n• eduskills virtual In ternship full stack web de velopmen t - Eduskills\nHONORS & A W ARD S\n• W on a gfg bagpack\n• Cleared tc s c ode vita r ound 1 - 2024\n1'

In [4]:
text = text.lower()
text = re.sub(f"[{string.punctuation}]", "", text)
text = re.sub(r"\d+", "", text)
text = re.sub(r"\s+", " ", text)
text = re.sub(r'http\S+|www\S+', '', text)   
text

'mohit gos w ami mohitgos w amigmailc om github linkedin leetcode portfolio educ a tion meer ut ins titute of engineering and technol og y a ugus t a u gus t bachelor of technology in computer science and enginnering aiml th sem meeru t cgp a curren t army public school march march senior secondary class cbse meeru t percen tage experience fre sher skill s programming languages c c python ja v a script librariesframeworks react t ail windc ss nodejs expressjs tools platforms v sc ode gitgithub databases mongodb pr o jec t s opensource algo sprint link reactjs nodejs expressjs t ail windc ss shadcn mongodb web socke ts a full stack web applica tion f or c oding pr actice fea turing per sonalized c oding r ooms real time ba ttles leaderboar ds c ollabor a tive c ompiler and mcq challenges personal por tf ol oio website link react tail windc ss fr amer mo tion de veloped a per sonal portf olio website t o sho wcase my skills pr oject and achie vmen ts the website pr o vides a clean and modern user in terf ace using t ail wind c ss i t is full y responsive and highligh ts my technical e xpertise the website serves as a cen tr al hub f or sharing my w ork money ment or ai link react tail wind c ss fr amer mo tion buil t the responsive fr on tend f or mone y men t or ai a per sonal finance assistan t tha t uses ai t o pr o vide budge ting advice and st ock s insigh ts designed and implemen ted dynamic ui c omponen ts and ensured a user friendl y in terf ace using modern web design principles cer tific a tions • gfg challenge geeks for geeks • eduskills virtual in ternship full stack web de velopmen t eduskills honors a w ard s • w on a gfg bagpack • cleared tc s c ode vita r ound '

In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import nltk
from nltk.corpus import stopwords

In [6]:
df = pd.read_csv("UpdatedResumeDataSet.csv")
df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  962 non-null    object
 1   Resume    962 non-null    object
dtypes: object(2)
memory usage: 15.2+ KB

In [8]:
def remove_number(text):
    cleaned_text = ""
    for ch in text: 
        if not ch.isdigit(): 
            cleaned_text += ch

    return cleaned_text

df['Resume'] = df['Resume'].apply(remove_number)

df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay  to May  B.E   UIT-R...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills â¢ R â¢ Python â¢ SAP HANA â¢ Table...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [9]:
def remove_emoji (text):
    cleaned_text = ""
    for i in text: 
        if i.isascii(): 
            cleaned_text += i
    
    return cleaned_text

df['Resume'] = df['Resume'].apply(remove_emoji)
df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details \r\nMay  to May  B.E   UIT-R...
2  Data Science  Areas of Interest Deep Learning, Control Syste...
3  Data Science  Skills  R  Python  SAP HANA  Tableau  SAP HANA...
4  Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...

In [10]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{'ll', 'theirs', 'further', 'their', 'weren', "weren't", 'up', "needn't", 'haven', "should've", 'again', 'by', 'me', 'until', 'above', 'too', 'aren', "she'd", "wouldn't", 'on', 'than', "he'll", 'being', 'before', 'an', 'hadn', 'have', 'was', 'will', 'to', 'couldn', 're', "wasn't", 'are', 'these', 'had', "i've", 'more', 'where', 'few', 'doesn', 'mightn', 'if', 'only', 'after', "isn't", "you'd", 'o', 'hasn', 'what', 'whom', "doesn't", 'yourselves', 'were', 'over', 'a', 'now', 'out', 've', "that'll", "he'd", 'of', 'no', 'having', "i'm", 'nor', 'own', 'off', "don't", 'do', 'at', 'in', 'herself', 'very', 'while', 'but', 'such', 'yours', 'its', 'all', 'itself', 'about', 'wasn', 'during', "you'll", 'needn', 'hers', 'most', 'for', 'against', 'here', 'he', 'as', "they'd", 'shouldn', "they'll", 'myself', 'she', 'through', "we'll", 's', 'his', 'any', 'when', "didn't", "hasn't", 'ain', "she'll", "they've", 'i', 'has', 'your', "shan't", "aren't", "you've", 'why', 'did', 'my', 'didn', 'then', 'be', 'so', 'once', 'that', 'am', 'or', 'it', 'shan', "it's", 'mustn', 'and', 'ma', "shouldn't", "won't", 'there', "i'd", 'wouldn', 'into', 'both', 'can', 'some', "mightn't", 'which', 'other', 'our', 'ourselves', 'won', 'doing', 'just', 't', "we're", 'don', 'below', 'how', "it'd", 'the', "haven't", 'isn', "he's", "they're", 'who', 'her', 'each', 'under', 'them', "couldn't", 'd', 'y', 'ours', 'him', "hadn't", 'is', 'himself', 'not', 'should', "she's", 'you', 'this', 'been', 'those', "mustn't", 'does', 'same', "you're", "i'll", 'from', 'we', 'm', 'yourself', 'between', "we've", 'with', "we'd", 'down', 'themselves', 'they', 'because', "it'll"}

In [12]:
def remove_stopwords (text):
    cleaned_text = []
    tokenized = text.split()

    for ch in tokenized: 
        if ch not in stop_words: 
            cleaned_text.append(ch)

    return ' '.join(cleaned_text)

df['Resume'] = df['Resume'].apply(remove_stopwords)
df.head()

       Category                                             Resume
0  Data Science  Skills * Programming Languages: Python (pandas...
1  Data Science  Education Details May May B.E UIT-RGPV Data Sc...
2  Data Science  Areas Interest Deep Learning, Control System D...
3  Data Science  Skills R Python SAP HANA Tableau SAP HANA SQL ...
4  Data Science  Education Details MCA YMCAUST, Faridabad, Hary...

In [13]:
df['Category'].unique()

array(['Data Science', 'HR', 'Advocate', 'Arts', 'Web Designing',
       'Mechanical Engineer', 'Sales', 'Health and fitness',
       'Civil Engineer', 'Java Developer', 'Business Analyst',
       'SAP Developer', 'Automation Testing', 'Electrical Engineering',
       'Operations Manager', 'Python Developer', 'DevOps Engineer',
       'Network Security Engineer', 'PMO', 'Database', 'Hadoop',
       'ETL Developer', 'DotNet Developer', 'Blockchain', 'Testing'],
      dtype=object)

In [ ]:
i = 0
category_to_number = {}